# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# project_area.py
# Created on: 2016-01-27 13:16:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
import time

#indir = "C:\Users\qzhao24\Desktop\Acitivty Space Data October 2015-From Scott\PointtoSDE"
#intermediate = "C:\Users\qzhao24\Desktop\Acitivty Space Data October 2015-From Scott\SDE_project"
#outdir = "C:\Users\qzhao24\Desktop\Acitivty Space Data October 2015-From Scott\SDE_to_area"


indir = "C:\Users\qzhao24\Desktop\Test1"
intermediate = "C:\Users\qzhao24\Desktop\Acitivty Space Data October 2015-From Scott\New SDE\SDE"
outdir = "C:\Users\qzhao24\Desktop\Acitivty Space Data October 2015-From Scott\New SDE\SDEarea"


for fshp in os.listdir(indir):

    start = time.time()

    if fshp.endswith(".shp"):
        file1 = fshp
        print file1


# Process: Directional Distribution (Standard Deviational Ellipse)
        arcpy.DirectionalDistribution_stats(os.path.join(indir,file1), os.path.join(intermediate,os.path.splitext(file1)[0][0:9]), "1_STANDARD_DEVIATION", "", "")
# Process: Calculate Areas
        arcpy.CalculateAreas_stats(os.path.join(intermediate,file1), os.path.join(outdir,file1))

    end = time.time()
    elapsed = end - start
    print elapsed