# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# Tb2T_math.py
# Created on: 2015-10-22 14:04:05.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import os
import arcpy

arcpy.env.overwriteOutput = True
# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

indir = "E:\\UHI\\Landsat\\thermal\\test"
outdir = "E:\\UHI\\Landsat\\thermal\\test\\test"
intermediate = "D:\\UHI\\intermediate"
# Local variables:
for ftif in os.listdir(indir):
    if ftif.endswith(".tif"):
        file = ftif
        print file
        output = os.path.join(outdir,os.path.splitext(file)[0] + "_celsius.tif")
        
# Process: minus
        arcpy.gp.Minus_sa(os.path.join(indir,file), 273.15, os.path.join(outdir,file))
