# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# extract.py
# Created on: 2015-10-22 11:27:33.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

import os

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

indir = "D:\\UHI\\thermal"
outdir = "D:\\UHI\\thermal\\masked"
mask = "D:\\UHI\\CAP_LandCoverLandsat_2011.tif"
for ftif in os.listdir(indir):
    if ftif.endswith(".TIF"):
        print ftif
        file = ftif
        output = os.path.join(outdir,os.path.splitext(file)[0] + "_masked.tif")
        print output
#		# Process: Extract by Mask
        arcpy.gp.ExtractByMask_sa(file, mask, output)
