# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# zonal_stats.py
# Created on: 2015-12-11 20:16:16.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os
from arcpy.sa import *

arcpy.env.overwriteOutput = True

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

inimg = "E:\\UHI\\Landsat\\thermal\\temperature(c)"
inzone = "E:\\UHI\\NLCD"
outdir = "E:\\UHI\\Temperature_summary"
# Local variables:
for ftif in os.listdir(inimg):
    if ftif.endswith(".tif"):
#        print file
        print ftif
#        if (int(ftif[9:13]) >= 2000 and int(ftif[9:13]) <= 2003):
#            zone = os.path.join(inzone,'nlcd_01_dissolve.shp')
#            img = os.path.join(inimg, ftif)
#            output = os.path.join(outdir,os.path.splitext(ftif)[0] + "_01.dbf")
#            print output
#        if (int(ftif[9:13]) >= 2004 and int(ftif[9:13]) <= 2008):
#            zone = os.path.join(inzone,'nlcd_06_dissolve.shp')
#            img = os.path.join(inimg, ftif)
#            output = os.path.join(outdir,os.path.splitext(ftif)[0] + "_06.dbf")
#            print output
#        elif (int(ftif[9:13]) >= 2009 and int(ftif[9:13]) <= 2011):
#            zone = os.path.join(inzone,'nlcd_11_dissolve.shp')
#            img = os.path.join(inimg, ftif)
#            output = os.path.join(outdir,os.path.splitext(ftif)[0] + "_11.dbf")
#            print output
#        else:
#            continue
        if ftif == 'LT50370372003190PAC02_temperature.tif':
            zone = os.path.join(inzone,'nlcd_11_dissolve.shp')
            img = os.path.join(inimg, ftif)
            output = os.path.join(outdir,os.path.splitext(ftif)[0] + "_11.dbf")
            print output
# Process: Zonal Statistics as Table
            ZonalStatisticsAsTable(zone, "GRIDCODE", img, output, "DATA", "MEAN")